#!/bin/bash

# Toggle to pop-out a tile to top right to stay fixed on a display basis.

# Variables:
#   width   Optional. Width of the floating window. 
#   height  Optional. Height of the floating window.
#
# Behavior:
#   - If the window is already pinned, it will be unpinned and removed from the pop layer.
#   - If the window is not pinned, it will be floated, resized, moved, pinned, brought to top, and popped.

width=${1:-750}
height=${2:-420}

active=$(hyprctl activewindow -j)
pinned=$(echo "$active" | jq ".pinned")
addr=$(echo "$active" | jq -r ".address")
window="address:$addr"


if [[ $pinned == "true" ]]; then
  
  hyprctl dispatch "hl.dsp.window.pin({ action = 'toggle', window = '$window' })"
  hyprctl dispatch "hl.dsp.window.float({ action = 'toggle', window = '$window' })"
  hyprctl dispatch "hl.dsp.window.tag({ tag = 'pop', window = '$window' })"

elif [[ -n  "$addr" ]]; then
  hyprctl dispatch "hl.dsp.window.float({ action = 'toggle', window = '$window' })"
  hyprctl dispatch "hl.dsp.window.resize({ x = $width, y = $height, window =  '$window' })"

  hyprctl dispatch "hl.dsp.window.move({ direction = 'r', window = '$window' })" 
  hyprctl dispatch "hl.dsp.window.move({ direction = 'u', window = '$window' })" 

  hyprctl dispatch "hl.dsp.window.pin({ action = 'toggle', window = '$window' })"
  hyprctl dispatch "hl.dsp.window.alter_zorder({ mode = 'top', window = '$window' })"
  hyprctl dispatch "hl.dsp.window.clear_tags({ window = '$window' })"
fi