#!/bin/bash

# checks if wifi device is enabled or not

if iwctl device wlan0 show | grep -qi "Powered               on"; then
    iwctl device wlan0 set-property Powered off
else
    iwctl device wlan0 set-property Powered on
fi