#! /bin/bash

STATE_FILE="$HOME/.config/hypr/monitor_switcher/state"

EXTEND_FILE="$HOME/.config/hypr/monitor_switcher/monitors_extended.lua"
MIRROR_FILE="$HOME/.config/hypr/monitor_switcher/monitors_mirror.lua"
CONFIG_FILE="$HOME/.config/hypr/secondary_monitors.lua"

if [ -f "$STATE_FILE" ] && [ "$(cat "$STATE_FILE")" = "mirror" ]; then
    cp "$EXTEND_FILE" "$CONFIG_FILE"
    notify-send "Secondary Monitor" "Switched to Extend" -u low -t 2500 --icon=computer
    echo "extended" > "$STATE_FILE"
    pkill waybar && hyprctl dispatch exec waybar
else
    cp "$MIRROR_FILE" "$CONFIG_FILE"
    notify-send "Secondary Monitor" "Switched to Mirror" -u low -t 2500 --icon=computer
    echo "mirror" > "$STATE_FILE"
fi